apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomsvincent/Kubernetes.git
    targetRevision: HEAD
    path: overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: mc-test
  syncPolicy:
    automated: {}